import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Megaphone, Pause, Play, Plus, Trash2 } from 'lucide-react';
import { apiFetch } from '../lib/api';

interface Ad { id: string; name: string; type: string; status: string; slot: string; priority: number; startAt?: string; endAt?: string; media?: { publicUrl: string } }
interface Response { data: Ad[]; meta: { total: number } }
const slots = ['HEADER_TOP', 'HOME_HERO_BELOW', 'HOME_FEED', 'ARTICLE_TOP', 'ARTICLE_MIDDLE', 'ARTICLE_BOTTOM', 'CATEGORY_TOP', 'SIDEBAR', 'FOOTER'];

export default function AdsPage() {
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name: '', type: 'IMAGE', slot: 'HOME_FEED', targetUrl: '', mediaId: '', priority: '0' });
  const { data } = useQuery<Response>({ queryKey: ['ads'], queryFn: () => apiFetch('/ads?limit=50') });
  const create = useMutation({ mutationFn: () => apiFetch('/ads', { method: 'POST', body: JSON.stringify({ ...form, priority: Number(form.priority), mediaId: form.mediaId || undefined, targetUrl: form.targetUrl || undefined }) }), onSuccess: () => { setShowForm(false); queryClient.invalidateQueries({ queryKey: ['ads'] }); } });
  const update = useMutation({ mutationFn: ({ id, action }: { id: string; action: string }) => action === 'delete' ? apiFetch(`/ads/${id}`, { method: 'DELETE' }) : apiFetch(`/ads/${id}/${action}`, { method: 'PATCH' }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['ads'] }) });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };

  return <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900"><Megaphone size={22} /> Advertisements</h1><p className="mt-1 text-sm text-gray-500">Control scheduled, targeted placements.</p></div><button onClick={() => setShowForm((value) => !value)} className="inline-flex items-center gap-2 rounded bg-primary-500 px-4 py-2 text-sm font-semibold text-white"><Plus size={16} /> New ad</button></div>
    {showForm && <form onSubmit={submit} className="mt-6 grid gap-3 rounded-lg border border-gray-200 bg-white p-5 md:grid-cols-3"><label className="text-sm font-medium">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium">Type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"><option>IMAGE</option><option>BANNER</option><option>HTML</option></select></label><label className="text-sm font-medium">Slot<select value={form.slot} onChange={(e) => setForm({ ...form, slot: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2">{slots.map((slot) => <option key={slot}>{slot}</option>)}</select></label><label className="text-sm font-medium">Media ID<input value={form.mediaId} onChange={(e) => setForm({ ...form, mediaId: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium">Target URL<input type="url" value={form.targetUrl} onChange={(e) => setForm({ ...form, targetUrl: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium">Priority<input type="number" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className="mt-1 w-full rounded border border-gray-300 px-3 py-2" /></label><div className="md:col-span-3"><button disabled={create.isPending} className="rounded bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Create ad</button></div></form>}
    <div className="mt-6 overflow-x-auto rounded-lg border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50"><tr>{['Name', 'Slot', 'Status', 'Schedule', 'Priority', 'Actions'].map((head) => <th key={head} className="whitespace-nowrap px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">{head}</th>)}</tr></thead><tbody className="divide-y divide-gray-200">{data?.data.map((ad) => <tr key={ad.id}><td className="px-4 py-3 font-medium text-gray-900">{ad.name}</td><td className="px-4 py-3 text-gray-600">{ad.slot}</td><td className="px-4 py-3"><span className="rounded bg-gray-100 px-2 py-1 text-xs font-semibold">{ad.status}</span></td><td className="whitespace-nowrap px-4 py-3 text-gray-600">{ad.startAt ? new Date(ad.startAt).toLocaleDateString() : 'Now'} - {ad.endAt ? new Date(ad.endAt).toLocaleDateString() : 'Open'}</td><td className="px-4 py-3">{ad.priority}</td><td className="px-4 py-3"><div className="flex gap-2">{ad.status === 'ACTIVE' ? <button title="Pause" onClick={() => update.mutate({ id: ad.id, action: 'pause' })} className="text-orange-600"><Pause size={16} /></button> : <button title="Activate" onClick={() => update.mutate({ id: ad.id, action: 'activate' })} className="text-green-600"><Play size={16} /></button>}<button title="Delete" onClick={() => window.confirm('Delete this advertisement?') && update.mutate({ id: ad.id, action: 'delete' })} className="text-red-600"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>
  </div>;
}
