import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { BarChart3, Eye, MessageCircle, MousePointerClick, Newspaper, Radio, Target } from 'lucide-react';
import { apiFetch } from '../lib/api';

interface Overview { totalViews: number; viewsToday: number; totalComments: number; commentsToday: number; activeAds: number; adImpressions: number; adClicks: number; publishedArticles: number }
interface Article { id: string; title: string; viewCount: number; commentCount: number; category?: { name: string } }
interface Location { id: string; name: string; type: string; totalViews: number }

export default function AnalyticsPage() {
  const [days, setDays] = useState('7');
  const { data: overview } = useQuery<Overview>({ queryKey: ['analytics-overview', days], queryFn: () => apiFetch(`/analytics/overview?days=${days}`) });
  const { data: topContent } = useQuery<Article[]>({ queryKey: ['analytics-content', days], queryFn: () => apiFetch(`/analytics/top-content?days=${days}&limit=8`) });
  const { data: locations } = useQuery<Location[]>({ queryKey: ['analytics-locations'], queryFn: () => apiFetch('/analytics/top-locations?limit=8') });
  const cards = [{ label: 'Views today', value: overview?.viewsToday, icon: Eye }, { label: 'Views in range', value: overview?.totalViews, icon: BarChart3 }, { label: 'Published articles', value: overview?.publishedArticles, icon: Newspaper }, { label: 'Comments', value: overview?.totalComments, icon: MessageCircle }, { label: 'Active ads', value: overview?.activeAds, icon: Target }, { label: 'Ad impressions', value: overview?.adImpressions, icon: Radio }, { label: 'Ad clicks', value: overview?.adClicks, icon: MousePointerClick }];
  return <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-gray-900"><BarChart3 size={22} /> Analytics</h1><p className="mt-1 text-sm text-gray-500">Newsroom performance and reader engagement.</p></div><select value={days} onChange={(e) => setDays(e.target.value)} className="rounded border border-gray-300 px-3 py-2 text-sm"><option value="1">Today</option><option value="7">7 days</option><option value="30">30 days</option></select></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map((card) => <div key={card.label} className="rounded-lg border border-gray-200 bg-white p-4"><card.icon size={18} className="text-primary-500" /><p className="mt-3 text-xs font-medium text-gray-500">{card.label}</p><p className="mt-1 text-2xl font-bold text-gray-900">{(card.value ?? 0).toLocaleString()}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-lg border border-gray-200 bg-white p-5"><h2 className="font-semibold text-gray-900">Top content</h2><div className="mt-4 divide-y divide-gray-100">{topContent?.map((article, index) => <div key={article.id} className="flex gap-3 py-3"><span className="text-sm text-gray-400">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-gray-800">{article.title}</p><p className="mt-1 text-xs text-gray-500">{article.viewCount.toLocaleString()} views · {article.commentCount} comments</p></div></div>)}</div></section><section className="rounded-lg border border-gray-200 bg-white p-5"><h2 className="font-semibold text-gray-900">Top districts and divisions</h2><div className="mt-4 divide-y divide-gray-100">{locations?.map((location) => <div key={location.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium text-gray-800">{location.name}</p><p className="text-xs text-gray-500">{location.type}</p></div><span className="text-sm font-semibold text-gray-700">{location.totalViews.toLocaleString()}</span></div>)}</div></section></div></div>;
}
